apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
