apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
